server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mouse_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ZYX0107..
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    port: 6379
    host: 192.168.43.129
    password: 123321
    timeout: 10000
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKeyId: LTAI5tAxcWxXwQhi6dPpdFqY
  accessKeySecret: h35w5iS0x9kZZv2Yta0ZDpmf7XYvOE
  bucketName: mouse-blog
